//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ledger
    {
        public string ACCOUNTNAME { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Description { get; set; }
        public string Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
    }
}
