//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBBALANCESHEETGROUP
    {
        public int BALANCESHEETGRPID { get; set; }
        public string BALANCESHEETGROUPNM { get; set; }
        public string BALANCESHEETGROUPTYPE { get; set; }
    }
}
