//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSALEDETAIL
    {
        public int SaleDetailId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<decimal> PurchaseRate { get; set; }
        public Nullable<decimal> SaleRate { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> GAmount { get; set; }
        public Nullable<decimal> Cd { get; set; }
        public Nullable<decimal> Td { get; set; }
        public Nullable<decimal> CdVal { get; set; }
        public Nullable<decimal> TdVal { get; set; }
        public Nullable<decimal> Tax1 { get; set; }
        public Nullable<decimal> Tax2 { get; set; }
        public Nullable<decimal> Tax3 { get; set; }
        public Nullable<decimal> Tax1Val { get; set; }
        public Nullable<decimal> Tax2Val { get; set; }
        public Nullable<decimal> Tax3Val { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> SaleAC { get; set; }
        public Nullable<int> SaleTaxAC { get; set; }
        public Nullable<int> SurchargeAC { get; set; }
        public Nullable<int> Tax1AC { get; set; }
        public Nullable<int> Tax2AC { get; set; }
        public Nullable<decimal> SurCharge { get; set; }
        public Nullable<decimal> SurChargeVal { get; set; }
    }
}
