//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSALE
    {
        public int SaleId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> Billdate { get; set; }
        public Nullable<int> BillNo { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<decimal> PurchaseRate { get; set; }
        public Nullable<decimal> SaleRate { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> GAmount { get; set; }
        public Nullable<decimal> Cd { get; set; }
        public Nullable<decimal> Td { get; set; }
        public Nullable<decimal> CdVal { get; set; }
        public Nullable<decimal> TdVal { get; set; }
        public Nullable<decimal> Tax1_ { get; set; }
        public Nullable<decimal> Tax2_ { get; set; }
        public Nullable<decimal> Tax3_ { get; set; }
        public Nullable<decimal> Tax1Val { get; set; }
        public Nullable<decimal> Tax2Val { get; set; }
        public Nullable<decimal> Tax3Val { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> PurchaseAC { get; set; }
        public Nullable<int> PurchaseTaxAC { get; set; }
        public Nullable<int> SurChargeAC { get; set; }
        public Nullable<int> Tax1AC { get; set; }
        public Nullable<int> Tax2AC { get; set; }
    }
}
