//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBITEMMASTERHEADER
    {
        public int ITEMID { get; set; }
        public string ITEMNAME { get; set; }
        public Nullable<int> BRANDID { get; set; }
        public Nullable<int> ITEMGROUPID { get; set; }
        public Nullable<int> PURTAXID { get; set; }
        public Nullable<int> SALETAXID { get; set; }
    }
}
