//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBITEMMASTERDETAIL
    {
        public int ItemMasterDetailId { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public Nullable<int> SIZEID { get; set; }
        public string BARCODE { get; set; }
        public Nullable<decimal> BASICRATE { get; set; }
        public Nullable<decimal> PURRATE { get; set; }
        public Nullable<decimal> SALERATE { get; set; }
        public Nullable<decimal> MRP { get; set; }
    }
}
