//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSALEHEADER
    {
        public int SaleId { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> BillNo { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
