//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPOLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBTAXCONFIG
    {
        public int TAXID { get; set; }
        public string TAXNAME { get; set; }
        public Nullable<int> SALE_PURACCOUNT { get; set; }
        public string SALETAXCALCULATION { get; set; }
        public Nullable<int> SALES_PURTAXACCOUNT { get; set; }
        public Nullable<int> SURCHARGEACCOUNT { get; set; }
        public Nullable<int> TAX1ACCOUNT { get; set; }
        public Nullable<int> TAX2ACCOUNT { get; set; }
        public Nullable<decimal> TAX1_ { get; set; }
        public Nullable<decimal> TAX2_ { get; set; }
        public Nullable<decimal> TAX3_ { get; set; }
        public Nullable<decimal> SURONTAX3 { get; set; }
        public string TAXTYPE { get; set; }
    }
}
